// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/ledger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetLedgerHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerHistoryRequest) Reset() {
	*x = GetLedgerHistoryRequest{}
	mi := &file_proto_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerHistoryRequest) ProtoMessage() {}

func (x *GetLedgerHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *GetLedgerHistoryRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_proto_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *LedgerEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LedgerEntry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LedgerEntry) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LedgerEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetLedgerHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerHistoryResponse) Reset() {
	*x = GetLedgerHistoryResponse{}
	mi := &file_proto_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerHistoryResponse) ProtoMessage() {}

func (x *GetLedgerHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *GetLedgerHistoryResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ledger.proto\x12\x06ledger\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"M\n" +
	"\x12GetBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\"8\n" +
	"\x17GetLedgerHistoryRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"o\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"I\n" +
	"\x18GetLedgerHistoryResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.ledger.LedgerEntryR\aentries2\xab\x01\n" +
	"\rLedgerService\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.ledger.GetBalanceRequest\x1a\x1a.ledger.GetBalanceResponse\x12U\n" +
	"\x10GetLedgerHistory\x12\x1f.ledger.GetLedgerHistoryRequest\x1a .ledger.GetLedgerHistoryResponseB3Z1github.com/tkaixinn/trade-settlement-engine/protob\x06proto3"

var (
	file_proto_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_proto_rawDescData []byte
)

func file_proto_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_proto_rawDescData
}

var file_proto_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ledger_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),        // 0: ledger.GetBalanceRequest
	(*GetBalanceResponse)(nil),       // 1: ledger.GetBalanceResponse
	(*GetLedgerHistoryRequest)(nil),  // 2: ledger.GetLedgerHistoryRequest
	(*LedgerEntry)(nil),              // 3: ledger.LedgerEntry
	(*GetLedgerHistoryResponse)(nil), // 4: ledger.GetLedgerHistoryResponse
}
var file_proto_ledger_proto_depIdxs = []int32{
	3, // 0: ledger.GetLedgerHistoryResponse.entries:type_name -> ledger.LedgerEntry
	0, // 1: ledger.LedgerService.GetBalance:input_type -> ledger.GetBalanceRequest
	2, // 2: ledger.LedgerService.GetLedgerHistory:input_type -> ledger.GetLedgerHistoryRequest
	1, // 3: ledger.LedgerService.GetBalance:output_type -> ledger.GetBalanceResponse
	4, // 4: ledger.LedgerService.GetLedgerHistory:output_type -> ledger.GetLedgerHistoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ledger_proto_init() }
func file_proto_ledger_proto_init() {
	if File_proto_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_proto = out.File
	file_proto_ledger_proto_goTypes = nil
	file_proto_ledger_proto_depIdxs = nil
}
