syntax = "proto3";

package ledger;

option go_package = "github.com/tkaixinn/trade-settlement-engine/proto";

service LedgerService {
  rpc GetBalance(GetBalanceRequest) returns (GetBalanceResponse);
  rpc GetLedgerHistory(GetLedgerHistoryRequest) returns (GetLedgerHistoryResponse);
}

message GetBalanceRequest {
  string account_id = 1;
}

message GetBalanceResponse {
  string account_id = 1;
  double balance = 2;
}

message GetLedgerHistoryRequest {
  string account_id = 1;
}

message LedgerEntry {
  string id = 1;
  string event_id = 2;
  double amount = 3;
  string created_at = 4;
}

message GetLedgerHistoryResponse {
  repeated LedgerEntry entries = 1;
}