// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/matching/matching.proto

package matching

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	OrderType     string                 `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_proto_matching_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_matching_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SubmitOrderRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *SubmitOrderRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *SubmitOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SubmitOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Fill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyAccountId  string                 `protobuf:"bytes,1,opt,name=buy_account_id,json=buyAccountId,proto3" json:"buy_account_id,omitempty"`
	SellAccountId string                 `protobuf:"bytes,2,opt,name=sell_account_id,json=sellAccountId,proto3" json:"sell_account_id,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fill) Reset() {
	*x = Fill{}
	mi := &file_proto_matching_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fill) ProtoMessage() {}

func (x *Fill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fill.ProtoReflect.Descriptor instead.
func (*Fill) Descriptor() ([]byte, []int) {
	return file_proto_matching_matching_proto_rawDescGZIP(), []int{1}
}

func (x *Fill) GetBuyAccountId() string {
	if x != nil {
		return x.BuyAccountId
	}
	return ""
}

func (x *Fill) GetSellAccountId() string {
	if x != nil {
		return x.SellAccountId
	}
	return ""
}

func (x *Fill) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Fill) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SubmitOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fills         []*Fill                `protobuf:"bytes,1,rep,name=fills,proto3" json:"fills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_proto_matching_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_matching_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitOrderResponse) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

var File_proto_matching_matching_proto protoreflect.FileDescriptor

const file_proto_matching_matching_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/matching/matching.proto\x12\bmatching\"\x98\x01\n" +
	"\x12SubmitOrderRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12\x1d\n" +
	"\n" +
	"order_type\x18\x03 \x01(\tR\torderType\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\"\x86\x01\n" +
	"\x04Fill\x12$\n" +
	"\x0ebuy_account_id\x18\x01 \x01(\tR\fbuyAccountId\x12&\n" +
	"\x0fsell_account_id\x18\x02 \x01(\tR\rsellAccountId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\";\n" +
	"\x13SubmitOrderResponse\x12$\n" +
	"\x05fills\x18\x01 \x03(\v2\x0e.matching.FillR\x05fills2]\n" +
	"\x0fMatchingService\x12J\n" +
	"\vSubmitOrder\x12\x1c.matching.SubmitOrderRequest\x1a\x1d.matching.SubmitOrderResponseB<Z:github.com/tkaixinn/trade-settlement-engine/proto/matchingb\x06proto3"

var (
	file_proto_matching_matching_proto_rawDescOnce sync.Once
	file_proto_matching_matching_proto_rawDescData []byte
)

func file_proto_matching_matching_proto_rawDescGZIP() []byte {
	file_proto_matching_matching_proto_rawDescOnce.Do(func() {
		file_proto_matching_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matching_matching_proto_rawDesc), len(file_proto_matching_matching_proto_rawDesc)))
	})
	return file_proto_matching_matching_proto_rawDescData
}

var file_proto_matching_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_matching_matching_proto_goTypes = []any{
	(*SubmitOrderRequest)(nil),  // 0: matching.SubmitOrderRequest
	(*Fill)(nil),                // 1: matching.Fill
	(*SubmitOrderResponse)(nil), // 2: matching.SubmitOrderResponse
}
var file_proto_matching_matching_proto_depIdxs = []int32{
	1, // 0: matching.SubmitOrderResponse.fills:type_name -> matching.Fill
	0, // 1: matching.MatchingService.SubmitOrder:input_type -> matching.SubmitOrderRequest
	2, // 2: matching.MatchingService.SubmitOrder:output_type -> matching.SubmitOrderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_matching_matching_proto_init() }
func file_proto_matching_matching_proto_init() {
	if File_proto_matching_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matching_matching_proto_rawDesc), len(file_proto_matching_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matching_matching_proto_goTypes,
		DependencyIndexes: file_proto_matching_matching_proto_depIdxs,
		MessageInfos:      file_proto_matching_matching_proto_msgTypes,
	}.Build()
	File_proto_matching_matching_proto = out.File
	file_proto_matching_matching_proto_goTypes = nil
	file_proto_matching_matching_proto_depIdxs = nil
}
